- name: Acte 1 - Configuration csr1000
  hosts: csr1000
  gather_facts: false

  tasks:
    - name: Nommage et activation des interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "Configuree par ansible"
            enabled: true
          - name: GigabitEthernet2
            description: "Configuree par ansible"
            enabled: true
          - name: GigabitEthernet3
            description: "Configuree par ansible"
            enabled: true
          - name: GigabitEthernet4
            description: "Configuree par ansible"
            enabled: true
        state: merged

    - name: Configuration des interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - ipv4:
              - dhcp:
                  enable: true
            name: GigabitEthernet1
          - ipv4:
              - address: 192.168.2.1/24
            name: GigabitEthernet2
          - ipv4:
              - address: 192.168.3.1/24
            name: GigabitEthernet3
          - ipv4:
              - address: 192.168.4.1/24
            name: GigabitEthernet4
        state: merged
    
    - name: Configuration du DHCP
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool LAN_POOL
          - network 192.168.2.0 255.255.255.0
          - default-router 192.168.2.1
          - dns-server 8.8.8.8
          - ip dhcp excluded-address 192.168.2.1
        before:
          - no ip dhcp pool LAN_POOL
        save_when: modified